-- Drop tenants.plan_price_override along with the grandfathering machinery it
-- served (server/billing.ts). Migration 0008 remapped pre-pivot paid tiers to
-- 'pro' and the code recorded what such a tenant ACTUALLY paid so the Billing
-- page wouldn't quote them Pro's price — but Zolto had no paying tenants when
-- 0008 ran and has none now, so that population never existed. Retired tiers
-- were never sellable either (PRICE_ENV holds only 'pro'), so no new legacy
-- subscription can be created through the product.
--
-- Safe because the column has no readers left and the platform is pre-launch.
-- If a grandfathered price is ever needed again, reintroduce it deliberately
-- rather than carrying an unread column and three unused env vars for years.
ALTER TABLE `tenants` DROP COLUMN `plan_price_override`;
