-- The "Made with Gwinn" credit becomes an opt-out rather than a plan side-effect.
--
-- Until now the credit was decided entirely by `PLAN_FEATURES[plan].whiteLabel`:
-- Free stores carried it (in /llms.txt, and nowhere else), Pro stores silently
-- dropped it. Two problems with that:
--
--   * A custom domain is Pro-only. So the storefronts where the Gwinn name is
--     least discoverable — someone else's domain, our HTML — were the exact ones
--     that never named it, to any shopper, crawler or AI agent.
--   * "Runs on Gwinn" appeared in the llms.txt brief and nowhere a human or a
--     search engine would ever see it. There was no footer credit and no
--     structured-data attribution at all.
--
-- So the credit now shows by default on every plan, and white-labelling buys the
-- *right to turn it off* rather than turning it off unasked. This column is that
-- switch. `tenant.updateSettings` refuses to set it without the plan feature,
-- and shared/attribution.ts ignores a stale `true` on a store that has since
-- dropped to Free — so a downgrade restores the credit with no backfill.
--
-- DEFAULT false = "show the credit", which is the new behaviour for every
-- existing row, Free and Pro alike.
ALTER TABLE `tenant_settings` ADD COLUMN `hide_platform_credit` boolean NOT NULL DEFAULT false;
